# This builds the dash app into a container and pushes it into the github container registry

name: build

on:
  
  push:
    #branches: [ "main" ]
    #tags: [ 'v*.*.*' ] # Publish server tags as releases.
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io # the github container registry
  IMAGE_NAME: ${{ github.repository }} # github.repository as <account>/<repo> i.e. danny-baker/atlas

jobs:
  
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      # Bake secrets into container before building it
      - name: Injecting GA4 tag
        run: sed -i "s/SECRET_GA4_TAG/$SECRET_GA4_TAG/" ./flask_app/dash_app/dash_html.py     
        env: 
          SECRET_GA4_TAG: ${{ vars.SECRET_GA4_TAG }}
      
      # Set Gunicorn workers
      - name: Set Gunicorn worker number
        run: sed -i "s/workers 1/$GUNICORN_WORKERS/" ./Dockerfile     
        env: 
          GUNICORN_WORKERS: ${{ vars.GUNICORN_WORKERS }}

      # Set Gunicorn threads
      - name: Set Gunicorn thread number
        run: sed -i "s/threads 1/$GUNICORN_THREADS/" ./Dockerfile     
        env: 
          GUNICORN_THREADS: ${{ vars.GUNICORN_THREADS }}

      # Bake in Azure blob config
      - name: Inject Azure storage account name
        run: sed -i "s/AZURE_STORAGE_ACCOUNT_NAME/'$AZURE_STORAGE_ACCOUNT_NAME'/" ./flask_app/dash_app/app.py
        env: 
            AZURE_STORAGE_ACCOUNT_NAME: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}

      # Bake in Azure blob config
      - name: Inject Azure storage account container name
        run: sed -i "s/AZURE_STORAGE_ACCOUNT_CONTAINER_NAME/'$AZURE_STORAGE_ACCOUNT_CONTAINER_NAME'/" ./flask_app/dash_app/app.py
        env: 
            AZURE_STORAGE_ACCOUNT_CONTAINER_NAME: ${{ vars.AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}

      # Bake in Azure blob credentials (using @ as delimiter as key contains / which is fucking seds params)
      - name: Inject Azure storage account key
        run: sed -i "s@AZURE_STORAGE_ACCOUNT_KEY@'$AZURE_STORAGE_ACCOUNT_KEY@'" ./flask_app/dash_app/app.py
        env: 
          AZURE_STORAGE_ACCOUNT_KEY: ${{ vars.AZURE_STORAGE_ACCOUNT_KEY }}
     
      # Testing. Check if substitutions worked (dangerous)
      - name: Check if substitutions worked. Printing first 100 lines
        run: head -100 ./flask_app/dash_app/app.py

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build the app docker image
        run: docker build . --tag ghcr.io/$IMAGE_NAME/atlas_app
        
      - name: Push app image to github container registry
        run: docker push ghcr.io/$IMAGE_NAME/atlas_app:latest
